name: build

on:
  workflow_run:
    workflows: ["security"]
    types: [completed]
    branches:
        - "main"
env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v4

      - name: Build and Run
        run: cargo run --release &
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

