name: main

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: securecart
        ports:
          - 5432:5432
        # optional health‐check so we can wait on it
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize Database Schema
        env:
          PGPASSWORD: postgres        # for non‐interactive authentication
        run: |
          psql \
            -h localhost \
            -U postgres \
            -d securecart \
            -f "$GITHUB_WORKSPACE/sql/actionsinit.sql"

      - name: Run Tests
        run: cargo test -- --nocapture
        env:
          RUST_LOG: debug
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/securecart
